apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-image-mirror
  labels:
    app: docker-image-mirror
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-image-mirror
  template:
    metadata:
      labels:
        app: docker-image-mirror
    spec:
      volumes:
      - name: registry-cache-storage
        hostPath:
          path: /data/docker-image-mirror/cache 
          type: DirectoryOrCreate                
      containers:
      # 1. 镜像代理容器
      - name: docker-image-mirror
        image: ghcr.io/zgfh/docker-image-mirror:latest
        imagePullPolicy: Always  # 改为 Always 强制拉取最新镜像
        ports:
        - containerPort: 5000
          hostPort: 5000       
        env:
        - name: CACHE_REGISTRY
          value: "127.0.0.1:5001"  
        - name: PROXY_ADDR
          value: ":5000"
        resources: {}

      # 2. 缓存镜像仓库容器
      - name: registry
        image: registry:2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5001  
        env:
        - name: REGISTRY_HTTP_ADDR
          value: "0.0.0.0:5001"
        # 消除警告，提供一个固定的 secret
        - name: REGISTRY_HTTP_SECRET
          value: "a-secret-for-registry"
        volumeMounts:
        - name: registry-cache-storage
          mountPath: /var/lib/registry 
        resources: {}
